import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'Emir Cokrlija',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full h-screen p-10">
          <div className="relative w-full h-full border-2 border-black">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
